require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/ba/ba_support/reaction_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/ba/ba_support/reaction_spec.rb'
