version: '3'

volumes:
  redis:

services:
  redis:
    image: redis:latest
    volumes:
      - redis:/data
  bot:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - TOKEN=
